project:
  type: website
  output-dir: docs

website:
  title: "Semba-blog"
  navbar:
    background: secondary
    right:
      - about.qmd
      - home.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com/
        
format:
  html:
    theme: cosmo
    css: styles.css
    highlight-style: espresso



