project:
  type: website
  output-dir: docs

website:
  title: "Semba-blog"
  site-url: https://semba-bot.github.io/semba-blog/
  description: "Conservation blogs"
  navbar:
    background: secondary
    right:
      - icon: rss
        href: index.xml
      - about.qmd
      - home.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com/
        
format:
  html:
    theme: cosmo
    css: styles.css
    highlight-style: espresso



